# URL del API externo que vas a consumir
api.usuarios.url=https://jsonplaceholder.typicode.com
api.auth.url=https://trxdvpy.akisi.com:8443
api.consulta.url=https://trxdvpy.akisi.com:8443
api.pago.url=https://trxdvpy.akisi.com:8443


# Timeout opcional
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000